sites_folder: 'saved_sites'
crawler:
  sites_folder_path: 'public/saved_sites'
  years:
    - 'current'
    - '2008'
    - '2003'
    - '1998'
    - '1994'
  errors:
    wget_failed: "Diese Seite kann leider nicht gespeichert werden, da dies der Betreiber nicht erlaubt. Wir bitten um dein Verständnis!"
