sites_folder: 'saved_sites'
crawler:
  sites_folder_path: 'public/saved_sites'
  years:
    - 'current'
    - '2008'
    - '2003'
    - '1998'
    - '1994'
  errors:
    wget_failed: "Diese Seite kann leider nicht gespeichert werden, da dies der Betreiber nicht erlaubt. Wir bitten um dein Verständnis!"
  widths:
    y_current: 1400
    y_2008: 1024
    y_2003: 1024
    y_1998: 800
    y_1994: 600
  height: 1000
introjs:
    tool: "<p><b>Willkommen im Analyse-Tool</b></p><p>Die angegebene Seite wird gerade analysiert und wichtige Elemente werden farbig markiert.</p><p>Navigiert man mit der <b>Maus</b> in dem hier hervorgehoben Bereich, werden Bereiche der Website angezeigt, in denen sich der Mauszeiger gerade befindet.</p><p>Mit einem <b>Linksklick</b> öffnet man ein Overlay, mit dem eventuell nicht erkannte Bereiche markiert oder auch Markierungen gelöscht werden können. Hier kann auch direkt in den Ebenen der Website gewechselt werden.</p><p>Um einen <b>erfolgreichen Umbau</b> garantieren zu können, müssen bestimmte Elemente markiert sein. Erkennt diese die automatische Analyse nicht, müssen diese manuell markiert werden.</p>"
    analyse: "Falls erforderlich, kann die Analyse manuell zurückgesetzt oder neu gestartet werden.<br><b>Achtung:</b> Alle bereits markierten Elemente werden dabei verworfen."
    color: "Hier kann man die einzelnen Farbinformationen der Seite entnehmen. Welche Farbe kommt wie häufig vor?"
    legend: "Die Legende zeigt die einzelnen Elemente des Analyse-Tools.<br>Ist das Element auf der Seite gefunden worden, kann mit Mausklickt in der Legende zum gewünschten Element navigiert werden."
    finish: "Sind alle benötigten Bereiche richtig markiert, kann mit diesem Button die Umwandlung der Website gestartet werden."
history:
  years:
    - '2012'
    - '2009'
    - '2008'
    - '2006'
    - '2003-2004'
    - '2000-2002'
    - '1999'
    - '1998'
    - '1996'
    - '1995'
    - '1993-1994'
    - '1991'
    - '1989-1990'
    - '1950-1983'
  texts:
    - 'Viele neue Technologien, wie zum Beispiel HTML 5.5 oder Full Screen API, werden entwickelt.'
    - 'Trotz der vielseitigen Kritik einer zu hohen Fehlertoleranz wird HTML 5 seit 2009 als Standard verwendet und konnte die meisten Probleme lösen, die durch Syntaxfehler in HTML 4 und XHTML 1.1 ausgelöst wurden.  Mit HTML 5 wurden viele Features zur Einbindung multimedialer Inhalte hinzugefügt. Ebenfalls wurden Tags eingeführt, um den semantischen Inhalt eines Dokuments zu garantieren.'
    - 'Google launchte 2008 einen eigenen Webbrowser, der ab 2008 im Krieg um die Marktherrschaft mitspielte. Schnell und sicher stellte der Leichtgewichtler einen starken Gegner im Kampf dar.'
    - 'Fünf Jahre nach der Veröffentlichung von IE 6, kam dann die 7. Version des Microsoft-Browsers auf die Bildschirme. Der IE verwendete auch Elemente, wie das Browsen in Tabs oder den Anti-Phishing-Schutz die man vormals bereits in Firefox finden konnte.'
    - 'Mit der Einführung von Safari stieg auch Apple 2003 in die Browser-Szene ein. Der zweite Browserkrieg startete mit der Einführung von Firefox 1.0. Das Bekanntwerden von Sicherheitslücken beim Internet Explorer führte dazu, dass Mozilla bereits wenige Monate nach Einführung ein Prozent des früheren Marktanteils des Internet Explorers gewonnen hatte. Mozilla und andere alternative Browser eroberten immer mehr Markanteile von Microsoft.'
    - 'Die Entwicklung von CSS3 begann 2000. Microsoft`s Internet Explorer hatte 2002 eine Reichweite von 95%, mit dem Vorteil, dass er automatisch mit dem Windows-Betriebssystem ausgeliefert wurde. Der erste Browser-Kampf endete also mit dem IE als klaren Sieger.'
    - 'Die sogenannten Browser-Kriege sind im Gange und viele neue Technologien, wie JavaScript und Ajax, werden entwickelt. Diese halfen dem Web-Design sich mit schnellen Schritten weiter zu entwickeln.'
    - 'Die CSS2-Spezifikationen wurden 1998 vom W3C als neuer Standard präsentiert. Netscape stellte nach verlorenem Kampf gegen den Internet Explorer den Sourcecode des Navigators öffentlich zur Verfügung in der Hoffnung, dass der Browser ein erfolgreiches Open Source Projekt wird.'
    - 'CSS1 wurde im Dezember 1996 veröffentlicht, doch damals kaum verwendet, da die Browser nur sehr wenige der CSS-Funktionen unterstützten. Die größte norwegische Telekommunikationsfirma Telenor veröffentlichte den Browser Opera.'
    - 'Im Jahr 1995 wurde HTML 3 geboren. Während dieser Zeit bekamen die DesignerInnen mehr Möglichkeiten um ihr Webdesign zu gestalten. Viele Websites wurden mit bunten Hintergründen versehen und enthielten animierte GIF-Bilder. Microsoft veröffentlichte 1995 einen eigenen Browser.'
    - 'Der Browser Mosaic stand mit der Einführung des Internets für die breite Masse im Jahr 1993 eng in Verbindung. Auch heute verwenden Browser noch Elemente des GUI`s (Graphical User Interfaces) von Mosaic. 1994 war HTML die einzige Auszeichnungssprache, deshalb konnten nur sehr einfache Layouts mit Texten, Tabellen und Links erstellt werden. Der erste kommerzielle Webbrowser war Netscape Navigator. Das 1994 gegründete W3C definierte HTML als Standard für die Entwicklung von Webseiten.'
    - 'Im März 1991 wurde der erste grafische Browser und WYSIWYG HTML-Editor von Tim Berners-Lee entwickelt. Der WorldWideWeb-Browser wurde später auf Nexus umbenannt, um Verwechslungen mit dem WWW-System zu vermeiden. Die erste Webseite wurde 1991 veröffentlicht.'
    - '1989 entwickelte Tim Berners-Lee im Schweizer Kernforschungsinstitut CERN das HTTP-Protokoll, mit dem Unmengen an Daten verwaltet werden sollten. Im November 1990 lief der erste Web-Browser, der WorldWideWeb genannt wurde.'
    - 'Die ursprünglichen Erfindungen, aus denen später das Internet entstand, reichen bis in die 1950er Jahre zurück. Bereits zu Beginn der 60er wurde eine Idee zur Übertragung von Datenpaketen entwickelt. Das erste E-Mail-Programm wurde 1971 entwickelt. Das erste Netzwerk war Arpanet, welches erstmals 1977 öffentlich vorgestellt wurde. 1983 gilt als Geburtsstunde des Internets.'
