sites_folder: 'saved_sites'
crawler:
  sites_folder_path: 'public/saved_sites'
  years:
    - 'current'
    - '2008'
    - '2003'
    - '1998'
    - '1994'
  errors:
    wget_failed: "Diese Seite kann leider nicht gespeichert werden, da dies der Betreiber nicht erlaubt. Wir bitten um dein Verständnis!"
history:
  years:
    - '2012'
    - '2009'
    - '2008'
    - '2006'
    - '2004'
    - '2003'
    - '2002'
    - '2000'
    - '1999'
    - '1998'
    - '1997'
    - '1996'
    - '1995'
    - '1994'
    - '1993'
    - '1991'
    - '1989-1990'
    - '1950-1983'
  texts:
    - '2012'
    - '2009'
    - '2008'
    - '2006'
    - '2004'
    - '2003'
    - '2002'
    - '2000'
    - '1999'
    - '1998'
    - '1997'
    - '1996'
    - '1995'
    - 'Die Geburststunde des World Wide Webs im Bezug auf Programmcode wird im Jahr 1994 angesiedelt. Damals war HTML die einzige Programmiersprache, die für das Webdesign verwendet wurde und deshalb konnten nur sehr einfache Layouts mit Texten, Tabellen und Links mit oder ohne kleine Grafiken erstellt werden. Der erste kommerzielle Webbrowser war Netscape Navigator und wurde 1994 von Marc Andressen, dem Chef-Softwareingenieur von Mosiac, entwickelt. Das 1994 gegründete W3C definierte HTML als Standard für die Programmierung von Webseiten. Das W3C setzte auch weitere Standards für Open Web Markup und Programmiersprachen wie z.B. JavaScript.'
    - 'Der Browser Mosaic stand eng in Verbindung mit der Einführung des Internets für die breite Masse. Auch heute verwenden Internet Explorer und Firefox noch Elemente des GUI`s (Graphical User Interfaces) von Mosaic. Browser: Mosaic'
    - 'Im März 1991 war die Erstellung des ersten Webbrowsers abgeschlossen. Der erste grafische Browser und WYSIWYG HTML-Editor wurde von Tim Berners-Lee, dem Erfinder des Webs, entwickelt. Der WorldWideWeb-Browser wurde später auf Nexus umbenannt, um Verwechslungen mit dem WWW-System zu vermeiden. Die erste Webseite wurde im August 1991 ebenfalls von Tim Berners-Lee veröffentlicht. Technologie: HTTP, HTML1, PostScript'
    - '1989 schlug Tim Berners-Lee im Schweizer Kernforschungsinstitut CERN ein hypertext-basiertes Dokumenten-Management vor, mit dem Unmengen an Daten verwaltet werden sollten. Technologie 1989: Videotext. Im November 1990 lief der erste Webserver, der von seinem Erfinder WorldWide-Web genannt wurde.'
    - 'Die ursprünglichen Erfindungen, aus denen später das Internet entstand, reichen bis in die 1950er Jahre zurück. Bereits zu Beginn der 60er wurde von Baum Baran die Idee der Paketvermittlung entwickelt, ohne die eine sichere Kommunikation nicht möglich wäre. Das erste Netzwerk war Arpanet, das diesen Namen erhielt, weil es von der amerikanischen Regierungsbehörde Arpa gesponsert wurde. Das erste E-Mail-Programm wurde 1971 von Ray Tomlinson entwickelt und im November 1977 wurde das Arpanet zum ersten Mal öffentlich vorgestellt, nachdem es inzwischen auf 111 angebundene Hosts, die auch außerhalb der USA lagen, angewachsen war. Die Geburtsstunde des Internets wird mit der Umstellung auf das Netzwerkprotokoll NCP und die Protokollfamilie TCP/IP angesehen, was am 1.1.1983 erfolgte.'